# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nlsnightmare/Documents/C++/GUI/OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nlsnightmare/Documents/C++/GUI/OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nlsnightmare/Documents/C++/GUI/OpenGL/CMakeFiles /home/nlsnightmare/Documents/C++/GUI/OpenGL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nlsnightmare/Documents/C++/GUI/OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nls-engine

# Build rule for target.
nls-engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nls-engine
.PHONY : nls-engine

# fast build rule for target.
nls-engine/fast:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/build
.PHONY : nls-engine/fast

# target to build an object file
src/GameManager.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/GameManager.o
.PHONY : src/GameManager.o

# target to preprocess a source file
src/GameManager.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/GameManager.i
.PHONY : src/GameManager.i

# target to generate assembly for a file
src/GameManager.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/GameManager.s
.PHONY : src/GameManager.s

# target to build an object file
src/LuaScript.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/LuaScript.o
.PHONY : src/LuaScript.o

# target to preprocess a source file
src/LuaScript.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/LuaScript.i
.PHONY : src/LuaScript.i

# target to generate assembly for a file
src/LuaScript.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/LuaScript.s
.PHONY : src/LuaScript.s

# target to build an object file
src/Window.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/Window.o
.PHONY : src/Window.o

# target to preprocess a source file
src/Window.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/Window.i
.PHONY : src/Window.i

# target to generate assembly for a file
src/Window.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/Window.s
.PHONY : src/Window.s

# target to build an object file
src/game/GameObject.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/game/GameObject.o
.PHONY : src/game/GameObject.o

# target to preprocess a source file
src/game/GameObject.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/game/GameObject.i
.PHONY : src/game/GameObject.i

# target to generate assembly for a file
src/game/GameObject.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/game/GameObject.s
.PHONY : src/game/GameObject.s

# target to build an object file
src/graphics/Camera.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Camera.o
.PHONY : src/graphics/Camera.o

# target to preprocess a source file
src/graphics/Camera.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Camera.i
.PHONY : src/graphics/Camera.i

# target to generate assembly for a file
src/graphics/Camera.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Camera.s
.PHONY : src/graphics/Camera.s

# target to build an object file
src/graphics/Sprite.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Sprite.o
.PHONY : src/graphics/Sprite.o

# target to preprocess a source file
src/graphics/Sprite.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Sprite.i
.PHONY : src/graphics/Sprite.i

# target to generate assembly for a file
src/graphics/Sprite.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/Sprite.s
.PHONY : src/graphics/Sprite.s

# target to build an object file
src/graphics/SpriteRenderer.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/SpriteRenderer.o
.PHONY : src/graphics/SpriteRenderer.o

# target to preprocess a source file
src/graphics/SpriteRenderer.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/SpriteRenderer.i
.PHONY : src/graphics/SpriteRenderer.i

# target to generate assembly for a file
src/graphics/SpriteRenderer.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/SpriteRenderer.s
.PHONY : src/graphics/SpriteRenderer.s

# target to build an object file
src/graphics/low_level/ArrayBuffer.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/ArrayBuffer.o
.PHONY : src/graphics/low_level/ArrayBuffer.o

# target to preprocess a source file
src/graphics/low_level/ArrayBuffer.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/ArrayBuffer.i
.PHONY : src/graphics/low_level/ArrayBuffer.i

# target to generate assembly for a file
src/graphics/low_level/ArrayBuffer.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/ArrayBuffer.s
.PHONY : src/graphics/low_level/ArrayBuffer.s

# target to build an object file
src/graphics/low_level/IndexBuffer.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/IndexBuffer.o
.PHONY : src/graphics/low_level/IndexBuffer.o

# target to preprocess a source file
src/graphics/low_level/IndexBuffer.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/IndexBuffer.i
.PHONY : src/graphics/low_level/IndexBuffer.i

# target to generate assembly for a file
src/graphics/low_level/IndexBuffer.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/IndexBuffer.s
.PHONY : src/graphics/low_level/IndexBuffer.s

# target to build an object file
src/graphics/low_level/Shader.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Shader.o
.PHONY : src/graphics/low_level/Shader.o

# target to preprocess a source file
src/graphics/low_level/Shader.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Shader.i
.PHONY : src/graphics/low_level/Shader.i

# target to generate assembly for a file
src/graphics/low_level/Shader.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Shader.s
.PHONY : src/graphics/low_level/Shader.s

# target to build an object file
src/graphics/low_level/Texture.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Texture.o
.PHONY : src/graphics/low_level/Texture.o

# target to preprocess a source file
src/graphics/low_level/Texture.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Texture.i
.PHONY : src/graphics/low_level/Texture.i

# target to generate assembly for a file
src/graphics/low_level/Texture.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/Texture.s
.PHONY : src/graphics/low_level/Texture.s

# target to build an object file
src/graphics/low_level/VertexArray.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/VertexArray.o
.PHONY : src/graphics/low_level/VertexArray.o

# target to preprocess a source file
src/graphics/low_level/VertexArray.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/VertexArray.i
.PHONY : src/graphics/low_level/VertexArray.i

# target to generate assembly for a file
src/graphics/low_level/VertexArray.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/VertexArray.s
.PHONY : src/graphics/low_level/VertexArray.s

# target to build an object file
src/graphics/low_level/stb_image.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/stb_image.o
.PHONY : src/graphics/low_level/stb_image.o

# target to preprocess a source file
src/graphics/low_level/stb_image.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/stb_image.i
.PHONY : src/graphics/low_level/stb_image.i

# target to generate assembly for a file
src/graphics/low_level/stb_image.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/graphics/low_level/stb_image.s
.PHONY : src/graphics/low_level/stb_image.s

# target to build an object file
src/main.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/main.o
.PHONY : src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/main.i
.PHONY : src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/main.s
.PHONY : src/main.s

# target to build an object file
src/physics/BoxCollider2D.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/BoxCollider2D.o
.PHONY : src/physics/BoxCollider2D.o

# target to preprocess a source file
src/physics/BoxCollider2D.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/BoxCollider2D.i
.PHONY : src/physics/BoxCollider2D.i

# target to generate assembly for a file
src/physics/BoxCollider2D.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/BoxCollider2D.s
.PHONY : src/physics/BoxCollider2D.s

# target to build an object file
src/physics/PhysicsEngine.o:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/PhysicsEngine.o
.PHONY : src/physics/PhysicsEngine.o

# target to preprocess a source file
src/physics/PhysicsEngine.i:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/PhysicsEngine.i
.PHONY : src/physics/PhysicsEngine.i

# target to generate assembly for a file
src/physics/PhysicsEngine.s:
	$(MAKE) -f CMakeFiles/nls-engine.dir/build.make CMakeFiles/nls-engine.dir/src/physics/PhysicsEngine.s
.PHONY : src/physics/PhysicsEngine.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nls-engine"
	@echo "... src/GameManager.o"
	@echo "... src/GameManager.i"
	@echo "... src/GameManager.s"
	@echo "... src/LuaScript.o"
	@echo "... src/LuaScript.i"
	@echo "... src/LuaScript.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/game/GameObject.o"
	@echo "... src/game/GameObject.i"
	@echo "... src/game/GameObject.s"
	@echo "... src/graphics/Camera.o"
	@echo "... src/graphics/Camera.i"
	@echo "... src/graphics/Camera.s"
	@echo "... src/graphics/Sprite.o"
	@echo "... src/graphics/Sprite.i"
	@echo "... src/graphics/Sprite.s"
	@echo "... src/graphics/SpriteRenderer.o"
	@echo "... src/graphics/SpriteRenderer.i"
	@echo "... src/graphics/SpriteRenderer.s"
	@echo "... src/graphics/low_level/ArrayBuffer.o"
	@echo "... src/graphics/low_level/ArrayBuffer.i"
	@echo "... src/graphics/low_level/ArrayBuffer.s"
	@echo "... src/graphics/low_level/IndexBuffer.o"
	@echo "... src/graphics/low_level/IndexBuffer.i"
	@echo "... src/graphics/low_level/IndexBuffer.s"
	@echo "... src/graphics/low_level/Shader.o"
	@echo "... src/graphics/low_level/Shader.i"
	@echo "... src/graphics/low_level/Shader.s"
	@echo "... src/graphics/low_level/Texture.o"
	@echo "... src/graphics/low_level/Texture.i"
	@echo "... src/graphics/low_level/Texture.s"
	@echo "... src/graphics/low_level/VertexArray.o"
	@echo "... src/graphics/low_level/VertexArray.i"
	@echo "... src/graphics/low_level/VertexArray.s"
	@echo "... src/graphics/low_level/stb_image.o"
	@echo "... src/graphics/low_level/stb_image.i"
	@echo "... src/graphics/low_level/stb_image.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/physics/BoxCollider2D.o"
	@echo "... src/physics/BoxCollider2D.i"
	@echo "... src/physics/BoxCollider2D.s"
	@echo "... src/physics/PhysicsEngine.o"
	@echo "... src/physics/PhysicsEngine.i"
	@echo "... src/physics/PhysicsEngine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

